### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by pktiuk** [impleotv/gstreamer-klv-plugins-release#2]
Hello @impleotv ,

what is the license of this repository? I don't know whether can I use this plugin in my projects.

**Comment by impleotv** [comment]
Hi there,

The plugins are free, but they use the [MisbCore library](https://impleotv.com/products/sdks/misbcoresdk/), which is a commercial product.... 

Thanks,

Alex

**Comment by pktiuk** [comment]
Thank you for answer
